### ISSUE TITLE
Limit observations on map to _vespa velutina_ (nest & observation)

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#276] opened 2019-05-22 10:38 UTC
Currently, the map shows all observation instead of _vespa velutina_ only. Should be adjusted as long as https://github.com/inbo/vespa-watch/issues/108 is not implemented (which would make the species selection possible).

**Comment by peterdesmet** [comment] 2019-05-22 13:30
Also extend end date to today (and not first day of the month)

**Comment by peterdesmet** [comment] 2019-05-25 13:03
@bartaelterman @stijnvanhoey see https://github.com/inbo/vespa-watch/issues/293#issuecomment-495916821: Vespa crabro still ends up on the map, so this bug is either not resolved or not deployed on production.

**Comment by bartaelterman** [comment] 2019-06-03 09:56
See my comment on #293 
I suspect a caching issue as this issue seems fixed for me on production. Can you verify again @peterdesmet ?

**Comment by bartaelterman** [comment] 2019-06-03 10:17
Confirmed with @KarelSchoonvaere

**Comment by KarelSchoonvaere** [comment] 2020-06-11 15:48
Re-opening this issue because it's happening again: false positive observations that are reported as Asian hornet individual or nest but validated as another species are currenly shown on the homepage map. 
Can someone of the developers look into it? The high number of false observations is causing some hullabaloo in the media. 
@niconoe 
@peterdesmet 

Thanks!

**Comment by peterdesmet** [comment] 2020-06-12 07:11
@niconoe, I think the map is still only showing records with `vv_confirmed` (which is good), but it seems that `vv_confirmed` is assigned to records like these: https://www.inaturalist.org/observations/42009726

That record was first identified as V. velutina and one person agreed (probably leading to `vv_confirmed`?), but after that a whole number of people marked it as V. crabro. The record on our side still have V. velutina with `vv_confirmed` however: why is that information not syncing back?

**Comment by niconoe** [comment] 2020-06-12 09:42
Thanks, I'm working on it. Debugging this two-ways sync in production is a bit nightmarish, so it might take a few days.

**Comment by peterdesmet** [comment] 2020-06-12 09:46
Potentially related to:

#371

#354

**Comment by KarelSchoonvaere** [comment] 2020-06-17 12:26
Chart is overwhelmed by observations. News papers and beekeeping organisations are picking this up as a massive spread year of Vv while that's not the case. Can this be fixed a.s.a.p. please?

**Comment by niconoe** [comment] 2020-06-17 12:38
Hi @KarelSchoonvaere. Sorry about it, there are problems with the two-way sync, I'm working on this.

**Comment by niconoe** [comment] 2020-06-24 07:29
This issue (after reopening) is indeed a duplicate of #371. That's finally fixed.

**Closed by niconoe** 2020-06-24 07:29 UTC
Labels: homepage :house:
