### ISSUE TITLE
Time zone issues in string representation of observations

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#58] opened 2018-11-12 09:39 UTC
An observation set (in the admin) at midnight+30 minutes appear as the previous day, in the string representation in the model.

**Comment by niconoe** [comment] 2018-11-12 09:41
Attempt to fix seems not totally successful. Need to investigate deeper.

**Comment by bartaelterman** [comment] 2018-11-15 12:51
@niconoe I cannot reproduce this. Maybe that's because I have dropped my database and recreated everything (also importing all observations again) now that the `USE_TZ` setting is set.

E.g. I've created an observation with time "2018-01-01 00:30:00". In the database, those dates are now stored with a timezone: `2018-01-01 00:30:00+01`. As expected, because at the first of Jan, we have winter time so the time zone should be +01.

The webapp displays that as `Jan. 1, 2018, 12:30 a.m.` which seems correct to me.

If I change that to June, the database stores it as `2018-06-01 00:30:00+02` and the display on the webapp is also ok.

Closing the issue now. Feel free to reopen if it still exists on your side.

**Closed by bartaelterman** 2018-11-15 12:51 UTC
Labels: bug
