### ISSUE TITLE
New datetime fields get naive datetimes

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#318] opened 2019-07-19 08:46 UTC
I got:

```
RuntimeWarning: DateTimeField IndividualPicture.datetime received a naive datetime (2000-01-01 00:00:00) while time zone support is active.

DateTimeField NestPicture.datetime received a naive datetime (2000-01-01 00:00:00) while time zone support is active
```

when migrating, is it from the field default value? We can probably get rid of the warning using something like:

```
from django.utils import timezone
timezone.now()
```

**Comment by bartaelterman** [comment] 2019-07-25 07:14
Hmmm... This is indeed from the `IndividualPicture` and `NestPicture` models. I used the `auto_now_add` attribute of the `DateTimeField`.
From the django docs:

>Note
>
>The auto_now and auto_now_add options will always use the date **in the default timezone** at the moment of creation or update. If you need something different, you may want to consider simply using your own callable default or overriding save() instead of using auto_now or auto_now_add; or using a DateTimeField instead of a DateField and deciding how to handle the conversion from datetime to date at display time.

Are you sure you have a default time zone set locally?

We can easily replace the `auto_now_add=True` by a callable like: `auto_now_add=timezone.now` of course.

**Comment by bartaelterman** [comment] 2019-07-25 07:57
Discussed with @niconoe 

The warning is only shown during database migration: I provided a naive datetime as default value. That value is set on all pictures that are present in the database when the field is added. Since we don't know when those pictures were created, a bogus value was set (Jan 1st, 2000). The fact that that is naive shouldn't really bother: it's a bogus value anyway. Also, if you retrieve the value from the database (at least on my machine), you get it back _with_ timezone, so the issue is already resolved.
The field that was added sets the current datetime (with timezone) by default, so for new pictures, this warning won't be triggered.

Conclusion: closing this issue.

**Closed by bartaelterman** 2019-07-25 07:57 UTC
Labels: 🛁 cleanup
